spring:
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mysqlpractice
    username: root
    password: liguanda123456
    driver-class-name: com.mysql.cj.jdbc.Driver