spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlpractice
    username: root
    password: liguanda123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #global-config:
   # db-config:
    #  table-prefix:
  global-config:
    db-config:
      id-type: auto